
GET  http://localhost:3001/

###
GET  http://localhost:3001/testing

###

Get http://localhost:3010/

###

GET http://localhost:3010/contact

###

GET http://localhost:3010/about

###

GET http://localhost:3010/directions

###